import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/headers";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Chatz } from "@/components/chatz";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
       <div className="z-10 fixed">
      <Navbar />
      </div> 
        {children}
       <Chatz />
        </body>
    </html>
  );
}
